config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  root to: "posts#index"
  resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :post_comments, only: [:create, :destroy]
  end

  get  "posts/:id/post_comments"  => "post_comments#create", defaults: { format: 'json' }

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @user_name = User.find(current_user.id).name
    @comment = @post.post_comments.build(comment_params)
    if @comment.save
      respond_to do |format|
        format.html
        format.json
      end 
    else
      flash.now[:alert] = 'コメントの投稿に失敗しました。'
    end

    # render :index
  end

  def destroy
    @comment = PostComment.find(params[:id])
    @comment.destroy
    render :index
  end

  private

  def comment_params
    params.permit(:comment, :post_id).merge(user_id: current_user.id)
  end

end

app/views/post_comments/_form.html.haml
-# = form_with(model: [post, comment], url: item_comments_path(@post) ) do |f|
-#   = f.text_area :content, class: "input-mysize"
-#   = f.submit "送信", class: "btn btn-outline-dark comment-submit float-right"

app/views/post_comments/_index.html.haml
-# - comments.first(5).each do |comment|
-#   - unless comment.id.nil?
-#     %li.comment-container
-#       .comment-box
-#         .comment-avatar
-#           = attachment_image_tag comment.user, :profile_image, fallback: "no_image.jpg", class:"comment-image", size: "40x40"
-#         .comment-text
-#           %p= link_to "@#{comment.user.name}", users_user_path(comment.user.id)
-#           .comment-entry
-#             = comment.content
-#             - if comment.user == current_user
-#               = link_to item_comment_path(comment.item_id, comment.id), method: :delete, remote: true, class: "comment_destroy" do
-#                 %i.fas.fa-trash{:style => "color: black;"}
-#           %span.comment-date.pull-right
-#             = comment.created_at.strftime('%Y/%m/%d %H:%M:%S')

app/views/post_comments/index.js.haml
-# $("#comments_area").html("<%= j(render 'index', { comments: @comment.post.comments }) %>")
-# $("textarea").val('')