config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  root to: "posts#index"
  resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :post_comments, only: [:create, :destroy]
  end

  get  "posts/:id/post_comments"  => "post_comments#create", defaults: { format: 'json' }

end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :upload_image, ImageUploader

  validates :title, presence: true
  validates :access_url, presence: true
  validates :description, presence: true
  validates :user_id, presence: true, uniqueness: true

  belongs_to :user
  has_many :post_comments, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order(created_at: "DESC")
  end

  def new
    if Post.find_by(user_id: current_user.id)
      post = Post.find_by(user_id: current_user.id)
      redirect_to edit_post_path(post.id)
    else
      @post = Post.new
    end
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path, notice: 'もくもく会を投稿しました。'
    else
      flash.now[:alert] = '未入力の項目があります。'
      render :index
    end
  end

  def show
    @post = Post.find(params[:postId])
    @comments = @post.post_comments.joins(:user).select("
                  post_comments.id,
                  post_comments.comment,
                  post_comments.created_at,
                  users.name
                ").order(created_at: :asc)

    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
    @post = Post.find_by(user_id: current_user.id)
    @upload_image = @post.upload_image
  end

  def update
    if Post.find_by(user_id: current_user.id).update(post_params)
      redirect_to root_path, notice: '投稿内容を更新しました。'
    else
      flash.now[:alert] = '投稿内容を更新できませんでした。'
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path, notice: 'もくもく会の投稿を削除しました.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :access_url, :description, :upload_image).merge(user_id: current_user.id)
  end
end

app/views/posts/_show_modal.html.haml
.modal-content{id: "con#{post.id}"}
  .modal-title
    = "もくもく会 の詳細"
  .modal-post
    .modal-post__title
      タイトル
    .modal-post__content
      = "#{post.title}"
  .modal-post
    .modal-post__title
      説明欄
    .modal-post__content--scloll
      = safe_join(post.description.split("\n"), tag(:br))
  .modal-post
    .modal-post__title
      参加接続URL
    .modal-post__content
      = link_to "#{post.access_url}", "#{post.access_url}", target: :_blank
  .modal-post
    .modal-post__title
      主催者
    .modal-post__content.flex
      .modal-post__content__organizer__image
        - if post.user.uid != nil
          %img{src: "#{post.user.image}", class: "post-detail-image"}
        - else
          - if post.user.image?
            = image_tag post.user.image.to_s, class:"post-detail-image"
          - else
            = image_tag "men-icon.jpeg", class:"post-detail-image"
      .modal-post__content__organizer__name
        = "#{post.user.name}"

  .modal-post
    .modal-post__title
      コメント欄
    .modal-post__content
      .modal-post__content__comment--scloll
        %ul#target-show-comment
      .modal-post__post__comment
        = form_for post_post_comments_path(post), remote: true, format: 'json' do |f|
          = f.text_area :comment, class: "input-comment"
          = f.submit "送信", class: "btn btn-outline-dark comment-submit float-right", data:{id:"#{post.id}"}
  %p
  %a.modal-close.btn.btn-primary.text-white 閉じる

app/views/posts/_toppage.html.haml
.wrap
  = video_tag "top_movie.mp4", poster:"top_image.jpg",autoplay: true, loop: true, muted: true, id:"bg-video"
  .header-title

  .top-description
    %p 〜 人と人とを繋ぐ 〜
    %p オンラインもくもく会専用マッチングサービス
  .container-fluid
    .row
      .col-3
      .col-6
        .jumbotron.register-box
          .text-center.register-box-description
            『mokucchi』を今すぐ始めるにはこちら
          %br/
          .text-center
            = link_to user_twitter_omniauth_authorize_path, class:"btn btn-primary btn-block" do
              = icon('fab', 'twitter')
              Twitterアカウントで始める
          %br/
          .text-center
            = link_to new_user_registration_path, class:"btn btn-secondary btn-block" do
              = icon('far','envelope')
              メールアドレスで始める
          %br/
          %br/

        
          .row.account
            .col-xl-6.col-lg-12
              .account-view
                = "ゲスト用Twitterアカウント"
                %table
                  %tr
                    %td ID
                    %td パスワード
                  %tr
                    %td sample-portfolio
                    %td guestpass
            .col-xl-6.col-lg-12
              .account-view
                = "ゲスト用メールアドレス"
                %table
                  %tr
                    %td メールアドレス
                    %td パスワード
                  %tr
                    %td sample@gmail.com
                    %td password


          
      .col-3

app/views/posts/edit.html.haml
.container-fuluid
  .top-margin
    = render partial: "layouts/side-contents"

    .main-contents
      .title-box
        %h1.content-title もくもく会を主催する
      = form_with model:@post, class: "post-form" do |f|
        .form-group.mb-0
          = f.label :title, "イメージ画像（変更は画像をクリック）"
          .image_form
            .image_form__contents
              = f.label :upload_image, class: 'image_label' do
                .prev-contents
                  - if @upload_image.url.present?
                    .prev-content
                      = image_tag @upload_image.url, class: "prev-image post-prev-image"
                  - else
                    .prev-content
                      = image_tag "post_card_image.jpeg", class: "prev-image post-prev-image"
                = f.file_field :upload_image, class: 'hidden_file_field'

        .form-group
          = f.label :title, "タイトル"
          = f.text_field :title, class:"form-control", placeholder: "タイトル"
        .form-group
          = f.label :access_url, "接続URL（zoom, Whereby 等）"
          = f.text_field :access_url, class:"form-control", placeholder: "例：https://us04web.zoom.us/j/◯◯◯◯?pwd=◯◯◯◯"
        .form-group
          = f.label :description, "説明欄"
          = f.text_area :description, class:"form-control", placeholder: "もくもく会の内容・目的など", rows: "4"
        = f.submit "更新する", class:"btn btn-primary", id:"edit-post"
        = link_to "削除する", post_path(@post.id) ,class:"btn btn-secondary", method: :delete

app/views/posts/index.html.haml
- if user_signed_in?
  .container-fuluid
    = render partial: "layouts/side-contents"

    .main-contents
      .container.text-center
        .title-box
          %h1.content-title 開催中のもくもく会

        .card-box.card-deck
          - @posts.each do |post|
            .row.card-margin
              .card.postcard.border-primary
                - if post.upload_image.url
                  = image_tag post.upload_image.url, class: "postcard-img"
                - else
                  = image_tag "top_image.jpg", alt: "postcard-image", class: "postcard-img"
                .card-content.card-body
                  .card-title
                    = post.title
                  .card-text
                    %a.modal-open{data: {target:"con#{post.id}", id:"#{post.id}"}}
                      .post-details.btn.btn-primary 詳細
                      
                    = render partial: "show_modal",locals: { post: post }

- else
  = render partial: "toppage"

app/views/posts/new.html.haml
.container-fuluid
  .top-margin
    = render partial: "layouts/side-contents"

    .main-contents
      .title-box
        %h1.content-title オンラインもくもく会を主催する
      = form_with model: @post, class: "post-form" do |f|
        .form-group.mb-0
          = f.label :title, "イメージ画像（変更は画像をクリック）"
          .image_form
            .image_form__contents
              = f.label :upload_image, class: 'image_label' do
                .prev-contents
                  - if @post.nil?
                    .prev-content
                      = image_tag @upload_image.url, class: "prev-image post-prev-image"
                  - else
                    .prev-content
                      = image_tag "post_card_image.jpeg", class: "prev-image post-prev-image"
                = f.file_field :upload_image, class: 'hidden_file_field'

        .form-group
          = f.label :title, "タイトル"
          = f.text_field :title, class:"form-control", placeholder: "タイトル"
        .form-group
          = f.label :access_url, "接続URL(zoom, Whereby 等)"
          = f.text_field :access_url, class:"form-control", placeholder: "例：https://us04web.zoom.us/j/◯◯◯◯?pwd=◯◯◯◯"
        .form-group
          = f.label :description, "説明欄"
          = f.text_area :description, class:"form-control", placeholder: "もくもく会の内容・目的など", rows: "4"
        = f.submit "作成する", class:"btn btn-primary", id:"new-post"